[database]
# Use environment variable DATABASE_URL to override.
# Format: postgresql+psycopg2://<user>:<password>@<host>:<port>/<dbname>
url = "postgresql+psycopg2://postgres:tejas2027@localhost:5432/remote_workforce"

[auth]
# Simple admin passcode for demo (do NOT use in production)
admin_passcode = "admin123"

[app]
workday_start = "09:00"
late_threshold_minutes = 15
company_name = "Acme Corp"
